baseURL = "https://hugotex.vercel.app/"
title = "Less的创作"
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme="default"

[pagination]
  pagerSize = 3

[Params.author]
  name = "Less"
  abstract = """
  心灵触觉，山高路远
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  darkmode = true
